__title__ = 'tomb_migrate'
__summary__ = 'DB migration scripts for tomb'
__uri__ = 'http://github.com/tomborine/tomb_migrate'
__version__ = '0.0.1'
__author__ = 'John Anderson'
__email__ = 'sontek@gmail.com'
__license__ = 'MIT'
__copyright__ = '2015 John Anderson (sontek)'
